version: '3.8'

services:
  bot0:
    build: .
    environment:
      BOT_ID: 0
      DROPBOX_TOKEN: ${DROPBOX_TOKEN}
    container_name: bot0

  bot1:
    build: .
    environment:
      BOT_ID: 1
      DROPBOX_TOKEN: ${DROPBOX_TOKEN}
    container_name: bot1

  bot2:
    build: .
    environment:
      BOT_ID: 2
      DROPBOX_TOKEN: ${DROPBOX_TOKEN}
    container_name: bot2
